import { chromium } from '@playwright/test';
import { once } from 'node:events';
import { mkdirSync, readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import express from 'express';
import { resolve } from 'node:path';
import { openStore } from '../server/store.mjs';
import { createApp } from '../server/app.mjs';
import { hashPassword } from '../server/security.mjs';

const db = openStore(':memory:');
const fixtureData = readFileSync(new URL('../tests/fixtures/portfolio.json', import.meta.url), 'utf8');
db.prepare('UPDATE portfolio SET content=? WHERE id=1').run(fixtureData);
const password = 'Browser-test-password-2026!';
db.prepare('INSERT INTO owner (id,email,password) VALUES(1,?,?)').run('browser@example.test', await hashPassword(password));
let code;
const app = await createApp({ db, secret: 'browser-test-secret'.repeat(5), appUrl: 'http://127.0.0.1:4179', sendCode: async (_, otp) => { code = otp; } });
const server = app.listen(4179, '127.0.0.1'); await once(server, 'listening');
const staticApp = express();
staticApp.get('/mypublic/data/portfolio.json', (req, res) => res.type('json').send(fixtureData));
staticApp.use('/mypublic', express.static(resolve('docs')));
const staticServer = staticApp.listen(4180, '127.0.0.1'); await once(staticServer, 'listening');
const browser = await chromium.launch({ headless: true, ...(process.platform === 'win32' ? { channel: 'chrome' } : {}) });
mkdirSync('.artifacts', { recursive: true });
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1050 } });
  const page = await context.newPage();
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://127.0.0.1:4179/');
  await page.locator('.project-card').last().waitFor(); assert.equal(await page.locator('.project-card').count(), 3);
  await page.screenshot({ path: '.artifacts/portfolio-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Data & automation', exact: true }).click(); assert.equal(await page.locator('.project-card').count(), 1);
  await page.getByRole('button', { name: 'ทั้งหมด', exact: true }).click();
  await page.getByRole('searchbox').fill('nothing-matches'); await page.locator('.empty-state').waitFor();
  await page.getByRole('searchbox').fill(''); await page.getByRole('link', { name: 'ดูรายละเอียด Personal portfolio', exact: true }).click();
  await page.waitForURL('**/project.html?id=sample-web'); await page.getByRole('heading', { name: 'Personal portfolio', exact: true }).waitFor();
  await page.getByRole('button', { name: 'คัดลอกลิงก์ผลงาน' }).click();
  await page.waitForFunction(() => document.querySelector('#share-status').textContent.length > 0);
  await page.reload(); await page.locator('#project-detail:not([hidden])').waitFor();
  await page.getByRole('link', { name: 'กลับไปดูผลงานทั้งหมด' }).click(); await page.locator('.project-card').last().waitFor();
  await page.setViewportSize({ width: 390, height: 844 }); await page.screenshot({ path: '.artifacts/portfolio-mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'Mobile horizontal overflow');
  await page.setViewportSize({ width: 1440, height: 1000 }); await page.goto('http://127.0.0.1:4179/login.html');
  await page.screenshot({ path: '.artifacts/login-desktop.png', fullPage: true });
  await page.getByLabel('อีเมลเจ้าของพอร์ต').fill('browser@example.test'); await page.getByLabel('รหัสผ่าน', { exact: true }).fill(password); await page.getByRole('button', { name: 'เข้าสู่ระบบ', exact: false }).click();
  await page.getByLabel('รหัสยืนยัน 6 หลัก').waitFor();
  assert.equal((await page.request.get('http://127.0.0.1:4179/api/admin/portfolio')).status(), 401);
  await page.screenshot({ path: '.artifacts/otp-desktop.png', fullPage: true });
  await page.getByLabel('รหัสยืนยัน 6 หลัก').fill(code); await page.getByRole('button', { name: 'ยืนยันและเข้าสู่ระบบ' }).click(); await page.waitForURL('**/admin.html'); await page.locator('#portfolio-form').waitFor();
  await page.getByLabel('ชื่อที่แสดง', { exact: true }).fill('Browser verified'); await page.getByRole('button', { name: 'บันทึกการเปลี่ยนแปลง' }).click(); await page.getByText('บันทึกโปรไฟล์และผลงานเรียบร้อยแล้ว', { exact: true }).waitFor();
  const response = await page.request.get('http://127.0.0.1:4179/api/portfolio'); assert.equal((await response.json()).profile.name, 'Browser verified');
  const firstEditor = page.locator('.project-editor').first();
  await firstEditor.locator('summary').click();
  await firstEditor.getByLabel('บทบาทของฉัน', { exact: true }).fill('ผู้ออกแบบและพัฒนา');
  await firstEditor.getByLabel('โจทย์และเป้าหมาย', { exact: true }).fill('รวบรวมผลงานให้ค้นหาและแชร์แยกเป็นรายโปรเจกต์ได้');
  await firstEditor.getByLabel('แนวทางและวิธีดำเนินงาน', { exact: true }).fill('ออกแบบหน้ารายละเอียดและใช้ลิงก์ถาวรตามรหัสผลงาน');
  await firstEditor.getByLabel('ผลลัพธ์และสิ่งที่ได้เรียนรู้', { exact: true }).fill('เปิดผลงานโดยตรงจากลิงก์ที่แชร์ได้');
  await page.getByRole('button', { name: 'บันทึกการเปลี่ยนแปลง' }).click(); await page.waitForFunction(() => !document.querySelector('#save').disabled);
  const detailPage = await page.context().newPage(); await detailPage.setViewportSize({ width: 1440, height: 1000 });
  await detailPage.goto('http://127.0.0.1:4179/project.html?id=sample-web'); await detailPage.getByRole('heading', { name: 'โจทย์และเป้าหมาย', exact: true }).waitFor();
  assert.equal(await detailPage.getByText('ผู้ออกแบบและพัฒนา', { exact: true }).count(), 1);
  await detailPage.screenshot({ path: '.artifacts/project-desktop.png', fullPage: true });
  await detailPage.setViewportSize({ width: 390, height: 844 }); await detailPage.screenshot({ path: '.artifacts/project-mobile.png', fullPage: true });
  assert.equal(await detailPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'Project detail mobile overflow');
  await detailPage.goto('http://127.0.0.1:4179/project.html?id=missing'); await detailPage.locator('#project-not-found:not([hidden])').waitFor();
  await firstEditor.getByLabel('เผยแพร่', { exact: true }).uncheck(); await page.getByRole('button', { name: 'บันทึกการเปลี่ยนแปลง' }).click(); await page.waitForFunction(() => !document.querySelector('#save').disabled);
  assert.equal(await firstEditor.locator('.project-permalink').isHidden(), true);
  await detailPage.goto('http://127.0.0.1:4179/project.html?id=sample-web'); await detailPage.locator('#project-not-found:not([hidden])').waitFor();
  await firstEditor.getByLabel('เผยแพร่', { exact: true }).check(); await page.getByRole('button', { name: 'บันทึกการเปลี่ยนแปลง' }).click(); await page.waitForFunction(() => !document.querySelector('#save').disabled);
  assert.equal(await firstEditor.locator('.project-permalink').isVisible(), true); await detailPage.close();
  await page.getByRole('button', { name: 'เพิ่มผลงาน' }).click(); assert.equal(await page.locator('.project-editor').count(), 4);
  await page.locator('.project-editor').last().getByRole('button', { name: 'นำผลงานออก' }).click(); await page.getByRole('button', { name: 'นำออก', exact: true }).click(); assert.equal(await page.locator('.project-editor').count(), 3);
  await page.getByRole('button', { name: 'บันทึกการเปลี่ยนแปลง' }).click(); await page.getByText('บันทึกโปรไฟล์และผลงานเรียบร้อยแล้ว', { exact: true }).waitFor();
  const downloadPromise = page.waitForEvent('download'); await page.getByRole('button', { name: 'ส่งออกไฟล์สำหรับ GitHub' }).click(); const download = await downloadPromise; assert.equal(download.suggestedFilename(), 'portfolio.json');
  await page.screenshot({ path: '.artifacts/admin-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'ออกจากระบบ', exact: true }).click(); await page.waitForURL('**/login.html');
  assert.equal((await page.request.get('http://127.0.0.1:4179/api/admin/portfolio')).status(), 401);
  await page.setViewportSize({ width: 390, height: 844 }); await page.screenshot({ path: '.artifacts/login-mobile.png', fullPage: true }); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.goto('http://127.0.0.1:4180/mypublic/'); await page.locator('.project-card').last().waitFor(); assert.equal(await page.locator('.project-card').count(), 3);
  await page.getByRole('link', { name: 'ดูรายละเอียด Personal portfolio', exact: true }).click();
  await page.waitForURL('**/mypublic/project.html?id=sample-web'); await page.locator('#project-detail:not([hidden])').waitFor();
  await page.reload(); await page.locator('#project-detail:not([hidden])').waitFor();
  await page.locator('#related-projects a').first().click(); await page.waitForURL('**/mypublic/project.html?id=sample-data'); await page.getByRole('heading', { name: 'Data workspace', exact: true }).waitFor();
  await page.goto('http://127.0.0.1:4180/mypublic/project.html'); await page.locator('#project-not-found:not([hidden])').waitFor();
  await page.goto('http://127.0.0.1:4180/mypublic/login.html'); await page.locator('#setup-note:not([hidden])').waitFor(); assert.equal(await page.locator('#login-form button[type=submit]').isDisabled(), true);
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: desktop/mobile, project permalinks/reload/share/related/not-found/drafts, detail editing, password + OTP, admin save/add/remove/export, logout, static repository subpath.');
} finally {
  await browser.close(); await new Promise(resolve => server.close(resolve)); await new Promise(resolve => staticServer.close(resolve)); db.close();
}
